[2022-11-25 09:34:03,171] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: GFA_Data_Engineering_Exam_dag01_ETL_pipeline.extract_transform_api manual__2022-11-25T09:34:00.923558+00:00 [queued]>
[2022-11-25 09:34:03,184] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: GFA_Data_Engineering_Exam_dag01_ETL_pipeline.extract_transform_api manual__2022-11-25T09:34:00.923558+00:00 [queued]>
[2022-11-25 09:34:03,185] {taskinstance.py:1357} INFO - 
--------------------------------------------------------------------------------
[2022-11-25 09:34:03,186] {taskinstance.py:1358} INFO - Starting attempt 1 of 1
[2022-11-25 09:34:03,186] {taskinstance.py:1359} INFO - 
--------------------------------------------------------------------------------
[2022-11-25 09:34:03,202] {taskinstance.py:1378} INFO - Executing <Task(PythonOperator): extract_transform_api> on 2022-11-25 09:34:00.923558+00:00
[2022-11-25 09:34:03,208] {standard_task_runner.py:52} INFO - Started process 7204 to run task
[2022-11-25 09:34:03,212] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'GFA_Data_Engineering_Exam_dag01_ETL_pipeline', 'extract_transform_api', 'manual__2022-11-25T09:34:00.923558+00:00', '--job-id', '67', '--raw', '--subdir', 'DAGS_FOLDER/MichalisKaratsioris_dag01.py', '--cfg-path', '/tmp/tmp91lowdoy', '--error-file', '/tmp/tmp0kkuo5hy']
[2022-11-25 09:34:03,213] {standard_task_runner.py:80} INFO - Job 67: Subtask extract_transform_api
[2022-11-25 09:34:03,272] {task_command.py:370} INFO - Running <TaskInstance: GFA_Data_Engineering_Exam_dag01_ETL_pipeline.extract_transform_api manual__2022-11-25T09:34:00.923558+00:00 [running]> on host c78bb2381ec5
[2022-11-25 09:34:03,353] {taskinstance.py:1572} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=GFA_Data_Engineering_Exam_dag01_ETL_pipeline
AIRFLOW_CTX_TASK_ID=extract_transform_api
AIRFLOW_CTX_EXECUTION_DATE=2022-11-25T09:34:00.923558+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-11-25T09:34:00.923558+00:00
[2022-11-25 09:34:04,231] {taskinstance.py:1890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/MichalisKaratsioris_dag01.py", line 48, in _extract_transform_api
    df = pd.read_csv(configuration_file_path)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 488, in _read
    return parser.read(nrows)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1047, in read
    index, columns, col_dict = self._engine.read(nrows)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 224, in read
    chunks = self._reader.read_low_memory(nrows)
  File "pandas/_libs/parsers.pyx", line 801, in pandas._libs.parsers.TextReader.read_low_memory
  File "pandas/_libs/parsers.pyx", line 857, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 843, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 1925, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Expected 3 fields in line 168, saw 4

[2022-11-25 09:34:04,249] {taskinstance.py:1401} INFO - Marking task as FAILED. dag_id=GFA_Data_Engineering_Exam_dag01_ETL_pipeline, task_id=extract_transform_api, execution_date=20221125T093400, start_date=20221125T093403, end_date=20221125T093404
[2022-11-25 09:34:04,268] {standard_task_runner.py:97} ERROR - Failed to execute job 67 for task extract_transform_api (Error tokenizing data. C error: Expected 3 fields in line 168, saw 4
; 7204)
[2022-11-25 09:34:04,313] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-11-25 09:34:04,369] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
