[2022-11-16 15:29:34,549] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: MSSQL_connection.transform manual__2022-11-16T15:29:22.640075+00:00 [queued]>
[2022-11-16 15:29:34,570] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: MSSQL_connection.transform manual__2022-11-16T15:29:22.640075+00:00 [queued]>
[2022-11-16 15:29:34,570] {taskinstance.py:1357} INFO - 
--------------------------------------------------------------------------------
[2022-11-16 15:29:34,571] {taskinstance.py:1358} INFO - Starting attempt 1 of 1
[2022-11-16 15:29:34,572] {taskinstance.py:1359} INFO - 
--------------------------------------------------------------------------------
[2022-11-16 15:29:34,595] {taskinstance.py:1378} INFO - Executing <Task(PythonOperator): transform> on 2022-11-16 15:29:22.640075+00:00
[2022-11-16 15:29:34,606] {standard_task_runner.py:52} INFO - Started process 1466 to run task
[2022-11-16 15:29:34,611] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'MSSQL_connection', 'transform', 'manual__2022-11-16T15:29:22.640075+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/pythonAirflowMSSQL.py', '--cfg-path', '/tmp/tmp12dut5kn', '--error-file', '/tmp/tmpp2w9wj_c']
[2022-11-16 15:29:34,613] {standard_task_runner.py:80} INFO - Job 23: Subtask transform
[2022-11-16 15:29:34,700] {task_command.py:370} INFO - Running <TaskInstance: MSSQL_connection.transform manual__2022-11-16T15:29:22.640075+00:00 [running]> on host 5036e10e6c0b
[2022-11-16 15:29:34,875] {taskinstance.py:1572} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=MSSQL_connection
AIRFLOW_CTX_TASK_ID=transform
AIRFLOW_CTX_EXECUTION_DATE=2022-11-16T15:29:22.640075+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-11-16T15:29:22.640075+00:00
[2022-11-16 15:29:34,903] {taskinstance.py:1890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/pythonAirflowMSSQL.py", line 45, in _transform
    df = pd.DataFrame(data, columns=['id', 'first_name', 'age'])
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/frame.py", line 730, in __init__
    raise ValueError("DataFrame constructor not properly called!")
ValueError: DataFrame constructor not properly called!
[2022-11-16 15:29:34,938] {taskinstance.py:1401} INFO - Marking task as FAILED. dag_id=MSSQL_connection, task_id=transform, execution_date=20221116T152922, start_date=20221116T152934, end_date=20221116T152934
[2022-11-16 15:29:34,961] {standard_task_runner.py:97} ERROR - Failed to execute job 23 for task transform (DataFrame constructor not properly called!; 1466)
[2022-11-16 15:29:34,989] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-11-16 15:29:35,060] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
