[2022-11-16 15:18:27,653] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: MSSQL_connection.transform manual__2022-11-16T15:18:19.368664+00:00 [queued]>
[2022-11-16 15:18:27,670] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: MSSQL_connection.transform manual__2022-11-16T15:18:19.368664+00:00 [queued]>
[2022-11-16 15:18:27,670] {taskinstance.py:1357} INFO - 
--------------------------------------------------------------------------------
[2022-11-16 15:18:27,672] {taskinstance.py:1358} INFO - Starting attempt 1 of 1
[2022-11-16 15:18:27,672] {taskinstance.py:1359} INFO - 
--------------------------------------------------------------------------------
[2022-11-16 15:18:27,693] {taskinstance.py:1378} INFO - Executing <Task(PythonOperator): transform> on 2022-11-16 15:18:19.368664+00:00
[2022-11-16 15:18:27,704] {standard_task_runner.py:52} INFO - Started process 1019 to run task
[2022-11-16 15:18:27,708] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'MSSQL_connection', 'transform', 'manual__2022-11-16T15:18:19.368664+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/pythonAirflowMSSQL.py', '--cfg-path', '/tmp/tmpi4lmmaln', '--error-file', '/tmp/tmphz3spztu']
[2022-11-16 15:18:27,710] {standard_task_runner.py:80} INFO - Job 13: Subtask transform
[2022-11-16 15:18:27,792] {task_command.py:370} INFO - Running <TaskInstance: MSSQL_connection.transform manual__2022-11-16T15:18:19.368664+00:00 [running]> on host 5036e10e6c0b
[2022-11-16 15:18:27,938] {taskinstance.py:1572} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=MSSQL_connection
AIRFLOW_CTX_TASK_ID=transform
AIRFLOW_CTX_EXECUTION_DATE=2022-11-16T15:18:19.368664+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-11-16T15:18:19.368664+00:00
[2022-11-16 15:18:27,981] {taskinstance.py:1890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/pythonAirflowMSSQL.py", line 47, in _transform
    df = df.loc[int(df['age']) < 8]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/series.py", line 185, in wrapper
    raise TypeError(f"cannot convert the series to {converter}")
TypeError: cannot convert the series to <class 'int'>
[2022-11-16 15:18:28,009] {taskinstance.py:1401} INFO - Marking task as FAILED. dag_id=MSSQL_connection, task_id=transform, execution_date=20221116T151819, start_date=20221116T151827, end_date=20221116T151828
[2022-11-16 15:18:28,026] {standard_task_runner.py:97} ERROR - Failed to execute job 13 for task transform (cannot convert the series to <class 'int'>; 1019)
[2022-11-16 15:18:28,043] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-11-16 15:18:28,096] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
