[2022-11-25 11:24:13,046] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: GFA_Data_Engineering_Exam_dag02_ETL_pipeline_airports.load manual__2022-11-25T11:23:48.249213+00:00 [queued]>
[2022-11-25 11:24:13,071] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: GFA_Data_Engineering_Exam_dag02_ETL_pipeline_airports.load manual__2022-11-25T11:23:48.249213+00:00 [queued]>
[2022-11-25 11:24:13,072] {taskinstance.py:1357} INFO - 
--------------------------------------------------------------------------------
[2022-11-25 11:24:13,073] {taskinstance.py:1358} INFO - Starting attempt 1 of 1
[2022-11-25 11:24:13,074] {taskinstance.py:1359} INFO - 
--------------------------------------------------------------------------------
[2022-11-25 11:24:13,113] {taskinstance.py:1378} INFO - Executing <Task(PythonOperator): load> on 2022-11-25 11:23:48.249213+00:00
[2022-11-25 11:24:13,133] {standard_task_runner.py:52} INFO - Started process 295 to run task
[2022-11-25 11:24:13,143] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'GFA_Data_Engineering_Exam_dag02_ETL_pipeline_airports', 'load', 'manual__2022-11-25T11:23:48.249213+00:00', '--job-id', '120', '--raw', '--subdir', 'DAGS_FOLDER/MichalisKaratsioris_dag02.py', '--cfg-path', '/tmp/tmpuxqnn1hv', '--error-file', '/tmp/tmpf88fxf8m']
[2022-11-25 11:24:13,146] {standard_task_runner.py:80} INFO - Job 120: Subtask load
[2022-11-25 11:24:13,271] {task_command.py:370} INFO - Running <TaskInstance: GFA_Data_Engineering_Exam_dag02_ETL_pipeline_airports.load manual__2022-11-25T11:23:48.249213+00:00 [running]> on host c78bb2381ec5
[2022-11-25 11:24:13,423] {taskinstance.py:1572} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=GFA_Data_Engineering_Exam_dag02_ETL_pipeline_airports
AIRFLOW_CTX_TASK_ID=load
AIRFLOW_CTX_EXECUTION_DATE=2022-11-25T11:23:48.249213+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-11-25T11:23:48.249213+00:00
[2022-11-25 11:24:15,374] {base.py:68} INFO - Using connection ID '***-mssql' for task execution.
[2022-11-25 11:24:15,880] {taskinstance.py:1890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "src/pymssql/_pymssql.pyx", line 461, in pymssql._pymssql.Cursor.execute
  File "src/pymssql/_mssql.pyx", line 1087, in pymssql._mssql.MSSQLConnection.execute_query
  File "src/pymssql/_mssql.pyx", line 1118, in pymssql._mssql.MSSQLConnection.execute_query
  File "src/pymssql/_mssql.pyx", line 1251, in pymssql._mssql.MSSQLConnection.format_and_run_query
  File "src/pymssql/_mssql.pyx", line 1789, in pymssql._mssql.check_cancel_and_raise
  File "src/pymssql/_mssql.pyx", line 1835, in pymssql._mssql.raise_MSSQLDatabaseException
pymssql._mssql.MSSQLDatabaseException: (245, b"Conversion failed when converting the nvarchar value '11.0' to data type int.DB-Lib error message 20018, severity 16:\nGeneral SQL Server error: Check messages from the SQL Server\n")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/MichalisKaratsioris_dag02.py", line 46, in _load
    hook.insert_rows("GFA_Data_Engineering_Exam.dbo.airports", result)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 378, in insert_rows
    cur.execute(sql, values)
  File "src/pymssql/_pymssql.pyx", line 479, in pymssql._pymssql.Cursor.execute
pymssql._pymssql.OperationalError: (245, b"Conversion failed when converting the nvarchar value '11.0' to data type int.DB-Lib error message 20018, severity 16:\nGeneral SQL Server error: Check messages from the SQL Server\n")
[2022-11-25 11:24:15,922] {taskinstance.py:1401} INFO - Marking task as FAILED. dag_id=GFA_Data_Engineering_Exam_dag02_ETL_pipeline_airports, task_id=load, execution_date=20221125T112348, start_date=20221125T112413, end_date=20221125T112415
[2022-11-25 11:24:15,959] {standard_task_runner.py:97} ERROR - Failed to execute job 120 for task load ((245, b"Conversion failed when converting the nvarchar value '11.0' to data type int.DB-Lib error message 20018, severity 16:\nGeneral SQL Server error: Check messages from the SQL Server\n"); 295)
[2022-11-25 11:24:15,997] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-11-25 11:24:16,090] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
