[2022-11-25 09:27:38,052] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: GFA_Data_Engineering_Exam_dag01_ETL_pipeline.load manual__2022-11-25T09:27:16.687557+00:00 [queued]>
[2022-11-25 09:27:38,085] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: GFA_Data_Engineering_Exam_dag01_ETL_pipeline.load manual__2022-11-25T09:27:16.687557+00:00 [queued]>
[2022-11-25 09:27:38,086] {taskinstance.py:1357} INFO - 
--------------------------------------------------------------------------------
[2022-11-25 09:27:38,087] {taskinstance.py:1358} INFO - Starting attempt 1 of 1
[2022-11-25 09:27:38,087] {taskinstance.py:1359} INFO - 
--------------------------------------------------------------------------------
[2022-11-25 09:27:38,131] {taskinstance.py:1378} INFO - Executing <Task(PythonOperator): load> on 2022-11-25 09:27:16.687557+00:00
[2022-11-25 09:27:38,143] {standard_task_runner.py:52} INFO - Started process 6875 to run task
[2022-11-25 09:27:38,150] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'GFA_Data_Engineering_Exam_dag01_ETL_pipeline', 'load', 'manual__2022-11-25T09:27:16.687557+00:00', '--job-id', '52', '--raw', '--subdir', 'DAGS_FOLDER/MichalisKaratsioris_dag01.py', '--cfg-path', '/tmp/tmpvvu6gq39', '--error-file', '/tmp/tmpjp6aobm7']
[2022-11-25 09:27:38,152] {standard_task_runner.py:80} INFO - Job 52: Subtask load
[2022-11-25 09:27:38,264] {task_command.py:370} INFO - Running <TaskInstance: GFA_Data_Engineering_Exam_dag01_ETL_pipeline.load manual__2022-11-25T09:27:16.687557+00:00 [running]> on host c78bb2381ec5
[2022-11-25 09:27:38,440] {taskinstance.py:1572} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=GFA_Data_Engineering_Exam_dag01_ETL_pipeline
AIRFLOW_CTX_TASK_ID=load
AIRFLOW_CTX_EXECUTION_DATE=2022-11-25T09:27:16.687557+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-11-25T09:27:16.687557+00:00
[2022-11-25 09:27:38,515] {taskinstance.py:1890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/MichalisKaratsioris_dag01.py", line 63, in _load
    df = pd.DataFrame(data, columns=["name", "iso2_code", "continent"])
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/frame.py", line 717, in __init__
    typ=manager,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/internals/construction.py", line 324, in ndarray_to_mgr
    _check_values_indices_shape_match(values, index, columns)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/internals/construction.py", line 393, in _check_values_indices_shape_match
    raise ValueError(f"Shape of passed values is {passed}, indices imply {implied}")
ValueError: Shape of passed values is (750, 1), indices imply (750, 3)
[2022-11-25 09:27:38,558] {taskinstance.py:1401} INFO - Marking task as FAILED. dag_id=GFA_Data_Engineering_Exam_dag01_ETL_pipeline, task_id=load, execution_date=20221125T092716, start_date=20221125T092738, end_date=20221125T092738
[2022-11-25 09:27:38,594] {standard_task_runner.py:97} ERROR - Failed to execute job 52 for task load (Shape of passed values is (750, 1), indices imply (750, 3); 6875)
[2022-11-25 09:27:38,645] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-11-25 09:27:38,747] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
